export EDITOR=vim

#export BASH_SILENCE_DEPRECATION_WARNING=1

source ~/.git-completion.bash

export GOPATH="$HOME/repos"
export PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/openssl/bin:$PATH:~/home/bin:$GOPATH/bin"

function _update_ps1() {
    PS1="$(/usr/local/bin/powerline-go \
	 -modules docker-context,kube,venv,user,host,ssh,cwd,git,newline,time,root \
	 -cwd-max-depth 4 \
	 -colorize-hostname \
	 -error $?)"
}

PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"

export LSCOLORS=GxBxHxDxFxHxHxHxHxCxCx
alias sudo='sudo '
alias vi='vim'
alias ls="ls -G"
alias repo='cd ~/repos/src/github.com'
alias sublime='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

alias vol0="ssh serviceadmin@vol0"
alias worker0="ssh serviceadmin@worker0"
alias worker1="ssh serviceadmin@worker1"
alias ns1="ssh serviceadmin@ns1"
alias ns2="ssh serviceadmin@ns2"
alias volnfs="sshfs workers@vol0:/share ~/nfs -o allow_other,default_permissions,IdentityFile=~/.ssh/workers,idmap=file,uidfile=.nfs_config/vol0_uid_map,nomap=ignore -C"

function ga() { git add -A; }
function gc() { git commit -m "$*"; }
function gac() { ga; gc $@; }
function gp() { git push;}


function sclist() { screen -list; }
function sckill() { screen -X -S ${1} quit; }
function gitco() { git log | grep Date | awk '{print " : "$4" "$3" "$6}' | uniq -c; }

# Set up virtualenvwrapper
eval "$(pyenv init -)"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export WORKON_HOME=$HOME/.pyenvs
pyenv virtualenvwrapper_lazy

#export WORKON_HOME=$HOME/.pyenvs
#export PROJECT_HOME=$HOME/repos/pyprojects
#source /usr/local/bin/pyenv-virtualenvwrapper

# Set up GPG
GPG_TTY=$(tty)
export GPG_TTY
