export EDITOR=vim

source ~/.git-completion.bash

export GOPATH="$HOME/repos"
export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/opt/openssl/bin:$PATH:~/home/bin:$GOPATH/bin"

function _update_ps1() {
    PS1="$(powerline-shell $?)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

export LSCOLORS=GxBxHxDxFxHxHxHxHxCxCx

alias vi='vim'
alias ls="ls -G"
alias repo='cd ~/repos/src/github.com'
alias sublime='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

function ga() { git add -A; }
function gc() { git commit -m "$*"; }
function gac() { ga; gc $@; }
function gp() { git push;}


function sclist() { screen -list; }
function sckill() { screen -X -S ${1} quit; }
function gitco() { git log | grep Date | awk '{print " : "$4" "$3" "$6}' | uniq -c; }

# Set up virtualenvwrapper
export WORKON_HOME=$HOME/.pyenvs
export PROJECT_HOME=$HOME/repos/pyprojects
source /usr/local/bin/virtualenvwrapper.sh

# Set up GPG
GPG_TTY=$(tty)
export GPG_TTY
