export EDITOR=vim

source ~/.git-completion.bash
source ~/.git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true

export GOPATH="$HOME/repos"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH:~/home/bin:$GOPATH/bin"

# Reset
CO='\[\e[0m\]'       # Color_Off

# Regular Colors
Black='\[\e[1;30m\]'        # Black
Red='\[\e[1;31m\]'          # Red
Green='\[\e[1;32m\]'        # Green
Yellow='\[\e[1;33m\]'       # Yellow
Blue='\[\e[1;34m\]'         # Blue
Purple='\[\e[1;35m\]'       # Purple
Cyan='\[\e[1;36m\]'         # Cyan
White='\[\e[1;37m\]'        # White

export PS1="$White[$Yellow\u$White@$Green\h $Purple[\t]$White:$Cyan\W$Red\$(__git_ps1)$White]\$ "

export LSCOLORS=GxBxHxDxFxHxHxHxHxCxCx

alias vi='vim'
alias ls="ls -G"
alias repo='cd ~/repos/src/github.com'
alias sublime='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'

function sclist() { screen -list; }
function sckill() { screen -X -S ${1} quit; }
function gitco() { git log | grep Date | awk '{print " : "$4" "$3" "$6}' | uniq -c; }

# Set up virtualenvwrapper
export WORKON_HOME=$HOME/.pyenvs
export PROJECT_HOME=$HOME/repos/pyprojects
source /usr/local/bin/virtualenvwrapper.sh


# In order for gpg to find gpg-agent, gpg-agent must be running, and there must be an env
# variable pointing GPG to the gpg-agent socket. This little script, which must be sourced
# in your shell's init script (ie, .bash_profile, .zshrc, whatever), will either start
# gpg-agent or set up the GPG_AGENT_INFO variable if it's already running.

# Add the following to your shell init to set up gpg-agent automatically for every shell
if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
    source ~/.gnupg/.gpg-agent-info
    export GPG_AGENT_INFO
else
    eval $(gpg-agent --daemon ~/.gnupg/.gpg-agent-info)
fi
