# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.hostname = "jenkins-seed"
    config.vm.box = "pexinator"
    config.vm.network :forwarded_port, guest: 8080, host: 4567
end
